---
authors:
  - Ruchi Pakhle (Ruchip16)
  - Rohit Thakur (rohitthakur2590)
dependencies:
  "ansible.netcommon": ">=8.1.0"
  "ansible.utils": ">=3.0.0"
  "ansible.scm": ">=2.0.0"
license_file: LICENSE
name: healthchecks
description: Ansible Network Healthchecks collection enable users to perform various network health checks and monitor tasks across different network platforms.
namespace: network
readme: README.md
repository: https://github.com/ansible-automation-platform/network.healthchecks
issues: https://github.com/ansible-automation-platform/network.healthchecks/issues
tags: [networking]
version: 2.0.0
