# fmt: off
[
  {
    "name": "eos_total_memory_kb",
    "getval": "^Total memory:\\s+(?P<memTotal>\\d+)\\s+kB",
    "shared": true,
    "result": {}
  },
  {
    "name": "eos_free_memory_kb",
    "getval": "^Free memory:\\s+(?P<memFree>\\d+)\\s+kB",
    "result": {
      "memory_health": {
        "total_mb": "{{ ((memTotal | int) / 1024) | round(2) }}",
        "free_mb": "{{ ((memFree | int) / 1024) | round(2) }}",
        "used_mb": "{{ (((memTotal | int) - (memFree | int)) / 1024) | round(2) }}"
      }
    }
  }
]
# fmt: on
