---
- name: Ping targets from NXOS device
  cisco.nxos.nxos_ping:
    dest: "{{ item }}"
    count: 3
  register: ping_result
  loop: "{{ ip_targets }}"
  ignore_errors: true

- name: Collect unreachable IPs (NXOS)
  ansible.builtin.set_fact:
    unreachable_ips: "{{ unreachable_ips | default([]) + [item] }}"
  when: ping_result.failed
  loop: "{{ ip_targets }}"
